const GET_EVENTS = 'GET_EVENTS';
const GET_EVENTS_FULFILLED = 'GET_EVENTS_FULFILLED';
const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

export default {
    GET_EVENTS, GET_EVENTS_ERROR, GET_EVENTS_FULFILLED
}
