const GET_EVENTS = 'GET_EVENTS';
const GET_EVENTS_FULFILLED = 'GET_EVENTS_FULFILLED';
const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

const UPDATE_FILTER = 'UPDATE_FILTER';
const UPDATE_FILTER_FULFILLED = 'UPDATE_FILTER_FULFILLED';

const UPDATE_TIME_LINE = 'UPDATE_TIME_LINE';

export default {
    GET_EVENTS, GET_EVENTS_ERROR, GET_EVENTS_FULFILLED,
    UPDATE_FILTER, UPDATE_FILTER_FULFILLED,
    UPDATE_TIME_LINE
}
