const GET_EVENTS = 'GET_EVENTS';
const GET_EVENTS_FULFILLED = 'GET_EVENTS_FULFILLED';
const GET_EVENTS_ERROR = 'GET_EVENTS_ERROR';

const UPDATE_FILTER = 'UPDATE_FILTER';
const UPDATE_FILTER_FULFILLED = 'UPDATE_FILTER_FULFILLED';

const UPDATE_TIME_LINE = 'UPDATE_TIME_LINE';

const UPDATE_MAP_CENTER = 'UPDATE_MAP_CENTER';

const OPEN_MARKER = 'OPEN_MARKER';
const CLOSE_MARKER = 'CLOSE_MARKER';

export default {
    GET_EVENTS, GET_EVENTS_ERROR, GET_EVENTS_FULFILLED,
    UPDATE_FILTER, UPDATE_FILTER_FULFILLED,
    UPDATE_TIME_LINE,
    UPDATE_MAP_CENTER,
    OPEN_MARKER,
    CLOSE_MARKER
}
